### ISSUE TITLE
Present reuse French Elections Platforms Tracking

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive.org#111]
- [x] Create a new `france-elections-platforms-tracking` page.
- [ ] Add an introductory text.
- [x] Send previous content with team as recipient through SendInBlue in order to have a consolidated view.
  - [x] Send french [Édition France Élections 7 avril 2022 ](https://sh1.sendinblue.com/ae3c72zlolpfe.html?t=1651736856)
  - [x] Send french [Édition France Élections 29 mars 2022](https://sh1.sendinblue.com/aebrlqzlolpfe.html?t=1651741289)
  - [x] Send french [Édition France Élections 23 mars 2022](https://sh1.sendinblue.com/aefzb2zlolpfe.html?t=1651742737)
  - [x] Send english [Memo France Elections of April 30, 2022](https://sh1.sendinblue.com/afdoxqzlolpfe.html?t=1651761783)
  - [x] Send english [Memo France Elections of April 22, 2022 
](https://sh1.sendinblue.com/af59j2zlolpfe.html?t=1651762086)  
  - [x] Send english [Edition France Elections April 14, 2022](https://sh1.sendinblue.com/aesmf2zlolpfe.html?t=1651761928)
  - [x] Send english [Edition France Elections April 7, 2022
](https://sh1.sendinblue.com/aeoepqzlolpfe.html?t=1651762172)
  - [x] Send english [Edition France Elections March 29, 2022
](https://sh1.sendinblue.com/aek70ezlolpfe.html?t=1651762251)
  - [x] Send english [Edition France Elections March 23, 2022
](https://sh1.sendinblue.com/afqc1qzlolpfe.html?t=1652089338)
- [ ] List all sent newsletters with sent date with a link to the content.
- [x] Add “French Elections Platforms Tracking” on homepage.
- [ ] Add short desc to homepage reuse block.
- [ ] Add pages (fr/en) to the sitemap.

**Comment by clementbiron** [comment]
Following the exchanges with Reset, I made a [pull request](https://github.com/ambanum/OpenTermsArchive.org/pull/126) to publish the reuse on the homepage.
